/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/alerts` | `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/contacts` | `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/deals` | `/deals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/alerts/[id]` | `/alerts/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/contacts/[id]` | `/contacts/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/deals/[id]` | `/deals/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/activity` | `/activity`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/alerts` | `/alerts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/contacts` | `/contacts`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/deals` | `/deals`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/tasks` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/alerts/[id]` | `/alerts/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/contacts/[id]` | `/contacts/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/deals/[id]` | `/deals/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/activity${`?${string}` | `#${string}` | ''}` | `/activity${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/alerts${`?${string}` | `#${string}` | ''}` | `/alerts${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/contacts${`?${string}` | `#${string}` | ''}` | `/contacts${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/deals${`?${string}` | `#${string}` | ''}` | `/deals${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/tasks${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/activity` | `/activity`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/alerts` | `/alerts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/contacts` | `/contacts`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/deals` | `/deals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | `${'/(app)'}/alerts/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/alerts/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/contacts/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/contacts/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/deals/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/deals/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/alerts/[id]` | `/alerts/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/contacts/[id]` | `/contacts/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/deals/[id]` | `/deals/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
